### ISSUE TITLE
Is there a service code?

### ISSUE THREAD

**Issue by dsalaza4** [wireapp/gitlab#1]
Hi,

I would like to test this integration, but it looks like there is not a service code. Can someone guide me on how to configure it?

Thanks!

**Comment by dkovacevic** [comment]
Hi

apologies for late reply. Somehow I missed this issue.

I did not publish the service code for this integration as Wire does not host GitLab service in Wire Cloud. We host only its (evil) tween brother GitHub bot.

In order to use GitLab bot you must deploy it to your server. Follow the steps in _lithium_:
https://github.com/wireapp/lithium#how-to-register-your-service-with-wire

Once you register as bot provider and obtain ProviderId and create your service and get the Service it then the Service code is: <ProviderId>:<ServiceId>. ProviderId followed by a column `:` then serviceID.

Alternatively: you can connect to Don (our meta bot) and he will help you with all these steps:
https://github.com/wireapp/don-bot

To test your GitLab service you should go to your Team Settings, Services tab and enter service code there. This will enable that service for your team. You and your team members will be then able to connect to that service by going people picker and services tab.

Hope this helps
